version: "2"
services:
  app:
    container_name: books
    restart: always
    build: .
    ports:
      - "80:3000"
    links:
      - mongodb
  mongodb:
    container_name: mongodb
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
