version: "2"
services:
  app:
    container_name: books
    image: 122238746683.dkr.ecr.us-east-2.amazonaws.com/books-app:latest
    ports:
      - "80:3000"
    links:
      - mongodb
  mongodb:
    container_name: mongodb
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
